### ISSUE TITLE
bug: table rendering broken when containing `inline code`

### ISSUE THREAD

**Issue by michamos** [MeanderingProgrammer/render-markdown.nvim#287]
### Neovim version (nvim -v)

0.10.2

### Neovim distribution

N/A

### Operating system

Linux

### Terminal emulator / GUI

kitty

### Describe the bug

When a table contains inline code between backticks (`like so`), the borders of the table are not drawn at the correct place on that line. It looks like the computation of the required line length is off.

Minimal example:

```markdown
|`foo`|bar|
|---|---|
|a|b|
```

is displayed as 
![image](https://github.com/user-attachments/assets/4887e3e1-1264-4294-9ebf-01ac8e6de49d)

### Expected behavior

the table border should be at the correct place

### Healthcheck output

```text
==============================================================================
render-markdown: require("render-markdown.health").check()

render-markdown.nvim [version] ~
- OK plugin 7.8.2
- OK neovim >= 0.10

render-markdown.nvim [configuration] ~
- OK valid

render-markdown.nvim [nvim-treesitter] ~
- OK installed
- OK markdown: parser installed
- OK markdown: highlight enabled
- OK markdown_inline: parser installed
- OK markdown_inline: highlight enabled
- WARNING latex: parser not installed
  - ADVICE:
    - Disable LaTeX support to avoid this warning by setting { latex = { enabled = false } }

render-markdown.nvim [icons] ~
- OK using: nvim-web-devicons

render-markdown.nvim [executables] ~
- WARNING latex2text: not installed
  - ADVICE:
    - Disable LaTeX support to avoid this warning by setting { latex = { enabled = false } }

render-markdown.nvim [conflicts] ~
- OK headlines: not installed
- OK obsidian: installed but should not conflict
```

### Plugin configuration

```lua
{ render_modes = true }
```

### Plugin error log

```text
N/A
```

### Confirmations

- [X] I have updated this plugin to the latest version using my plugin manager
- [X] I have provided the text contained in all screenshots as raw text in this issue. This means if there is a screenshot below it is the copy pasted contents of the file in the screenshot. I understand that my issue will be closed if I have not.

**Comment by MeanderingProgrammer** [comment]
Ah, that happens when the cells don't have space available on either side and that cell also happens to be >= the longest line in that column.

Updated the logic to handle this and create space when needed: https://github.com/MeanderingProgrammer/render-markdown.nvim/commit/786d643ac7a691515d401930b8850f596992725d.

**Comment by minhchu-warp** [comment]
@MeanderingProgrammer Hi, I'm still having this issue

```markdown

| Variable | Default | Description |
|---|---|---|
| DB_URL | file:./palette.db | Local SQLite file or remote Turso URL (libsql://...) |
| `DB_TOKEN`   | — | Auth token (required for remote Turso) |
| `PORT` | `8080` | HTTP listen port |
| `CACHE_SIZE` | `100` | Max LRU cache entries |
| `CACHE_TTL` | `1m` | Cache entry TTL |
| `RATE_LIMIT` | `60` | Max requests per IP per window |
| `RATE_WINDOW`   | `1m` | Rate limit window duration |
```

renders:

<img width="834" height="179" alt="Image" src="https://github.com/user-attachments/assets/e552c7b8-efc6-4818-bdb1-b08107fea135" />

As you can see DB_URL on the first row without backtick working fine. But rows with backtick are broken .
I'm using neovim 0.11.2, macOS, Ghostty.
Here is the healthcheck output:

```
render-markdown:                                                    7 ⚠️  1 ❌

render-markdown.nvim [versions] ~
- ✅ OK neovim >= 0.11
- ✅ OK tree-sitter ABI: 15
- ✅ OK plugin: 8.12.10

render-markdown.nvim [configuration] ~
- ✅ OK valid

render-markdown.nvim [tree-sitter markdown] ~
- ✅ OK parser: installed
- ✅ OK ABI: 14
- ✅ OK highlights: /opt/homebrew/Cellar/neovim/0.11.2/share/nvim/runtime/queries/markdown/highlights.scm
- ❌ ERROR highlighter: not enabled
  - ADVICE:
    - call vim.treesitter.start on markdown buffers

render-markdown.nvim [tree-sitter markdown_inline] ~
- ✅ OK parser: installed
- ✅ OK ABI: 14
- ✅ OK highlights: /opt/homebrew/Cellar/neovim/0.11.2/share/nvim/runtime/queries/markdown_inline/highlights.scm

render-markdown.nvim [tree-sitter html] ~
- ⚠️ WARNING parser: not installed
  - ADVICE:
    - disable html support to avoid this warning
    - require('render-markdown').setup({ html = { enabled = false } })
- ⚠️ WARNING ABI: unknown
  - ADVICE:
    - disable html support to avoid this warning
    - require('render-markdown').setup({ html = { enabled = false } })

render-markdown.nvim [tree-sitter latex] ~
- ⚠️ WARNING parser: not installed
  - ADVICE:
    - disable latex support to avoid this warning
    - require('render-markdown').setup({ latex = { enabled = false } })
- ⚠️ WARNING ABI: unknown
  - ADVICE:
    - disable latex support to avoid this warning
    - require('render-markdown').setup({ latex = { enabled = false } })

render-markdown.nvim [tree-sitter yaml] ~
- ⚠️ WARNING parser: not installed
  - ADVICE:
    - disable yaml support to avoid this warning
    - require('render-markdown').setup({ yaml = { enabled = false } })
- ⚠️ WARNING ABI: unknown
  - ADVICE:
    - disable yaml support to avoid this warning
    - require('render-markdown').setup({ yaml = { enabled = false } })

render-markdown.nvim [icons] ~
- ✅ OK using: nvim-web-devicons

render-markdown.nvim [latex] ~
- ⚠️ WARNING none installed: { "utftex", "latex2text" }
  - ADVICE:
    - disable latex support to avoid this warning
    - require('render-markdown').setup({ latex = { enabled = false } })

render-markdown.nvim [conflicts] ~
- ✅ OK headlines: not installed
- ✅ OK markview: not installed
- ✅ OK obsidian: installed but should not conflict

```
