### ISSUE TITLE
help: links not formatting as expected

### ISSUE THREAD

**Issue by emersonrp** [MeanderingProgrammer/render-markdown.nvim#458]
### Neovim version (nvim -v)

0.11.1

### Neovim distribution

n/a

### Description

I'm probably overlooking something trivially easy, but I just started tinkering with this plugin, and links aren't formatting as they seem to be intended to.  I haven't seen any config in the wiki/README that would affect this but I  might just be missing it.  Anyway, the little icon appears to the left as intended, but the bracketed text and parenthesized link target text remain unaffected, whereas it would seem that they're supposed to be hidden / consolidated into just the bracketed text.  I attach a screenshot of what I'm seeing.  This is in normal mode, in case it matters.  I haven't added any config at all - this is all defaults.

![Image](https://github.com/user-attachments/assets/5de459cb-4dc5-4230-9015-7ea6ad3b12c9)

Sorry if this is something simple that I've just missed.

**Comment by MeanderingProgrammer** [comment]
I'm going to guess this is because treesitter highlighting is not enabled.

Can you `:checkhealth render-markdown` and  paste the output in a comment.

**Comment by emersonrp** [comment]
Aha that was exactly the problem.  Tinkering with my treesitter config now to try to dtrt -- currently I haven't been using it for much of anything except dependencies for a couple of things and so it had no explicit config.  Still fiddling about to try to get the right thing to happen, but this was a great pointer, thank you.

(Also I have quashed the latex warnings per checkhealth's advice.)

```
   render-markdown:                     require("render-markdown.health").check()

   render-markdown.nvim [version]
   - ✅ OK plugin 8.5.9
   - ✅ OK neovim >= 0.11

   render-markdown.nvim [configuration]
   - ✅ OK valid

   render-markdown.nvim [treesitter]
   - ✅ OK markdown: parser installed
   - ✅ OK markdown: highlights ~/.local/share/nvim/lazy/nvim-treesitter/queries/markdown/highlights.scm
   - ❌ ERROR markdown: highlighter not enabled
     - ADVICE:
       - call vim.treesitter.start on markdown buffers
   - ✅ OK markdown_inline: parser installed
   - ✅ OK markdown_inline: highlights ~/.local/share/nvim/lazy/nvim-treesitter/queries/markdown_inline/highlights.scm
   - ⚠️ WARNING latex: parser not installed
     - ADVICE:
       - disable latex support to avoid this warning
       - require('render-markdown').setup({ latex = { enabled = false } })
   - ✅ OK html: parser installed

   render-markdown.nvim [icons]
   - ✅ OK using: nvim-web-devicons

   render-markdown.nvim [executables]
   - ⚠️ WARNING latex2text: not installed
     - ADVICE:
       - disable latex support to avoid this warning
       - require('render-markdown').setup({ latex = { enabled = false } })

   render-markdown.nvim [conflicts]
   - ✅ OK headlines: not installed
   - ✅ OK markview: not installed
   - ✅ OK obsidian: not installed
```
